### ISSUE TITLE
modify run.py so it takes command-line arguments

### ISSUE THREAD

**Issue by tomplex** [SimmonsRitchie/us_pop_extracter#1]
`run.py` should take command-line arguments which dictate where it puts output data, and perhaps also let the user specify certain states to download / process. Right now it's hard-coded to a place on your machine, which will break with an ugly error if I were to try to run this locally. =)

**Comment by SimmonsRitchie** [comment]
A good suggestion, Tom! This was just a little script I wrote for a specific project but you're right, I should add command line arguments to make this project reusable and to fix that error with the hardcoded path.

**Comment by SimmonsRitchie** [comment]
Added a CLI and published to PyPI.

**Comment by tomplex** [comment]
I love the new CLI & PyPI package! Looks great.

**Comment by SimmonsRitchie** [comment]
Thanks, Tom! 😊 It’s my first python package. Pretty basic, I know, but it was a great chance to finally understand setup.py, travis CI, etc. I learnt so much doing it.

I’m going to keep expanding this tool but I’m also now very eager to start building new packages.
